---
sudo: required
language: objective-c

# Reference for OS X Versions:
# https://docs.travis-ci.com/user/reference/osx/#macos-version
matrix:
  include:
    # Mojave (10.14)
    - os: osx
      osx_image: xcode11.3

before_script:
  # Clean up
  - rm ~/.gemrc ~/.gitconfig || true

  # Mock packages to save time
  - echo 'tap "narze/taps"' > etc/Brewfile
  - echo 'cask "whatpulse"' >> etc/Brewfile
  - echo 'cask "setapp"' >> etc/Brewfile
  - echo 'brew "zsh"' > etc/Brewfile-essentials

  - mkdir -p ~/Sync/laptop_local/tmuxinator
  - mkdir -p ~/Sync/laptop_local/mpd

script:
  - make
  - make bootstrap
  - make dotfiles
  - make code
  - make brew
  - make tools
  - make asdf
  - make sync
  - make update
