---
sudo: required
language: objective-c

# Reference for OS X Versions:
# https://docs.travis-ci.com/user/reference/osx/#macos-version
matrix:
  include:
    # Mojave (10.14)
    - os: osx
      osx_image: xcode11.3

script:
  # Clean up
  - rm ~/.gemrc ~/.gitconfig || true

  # Mock packages to save time
  - echo 'brew "zsh"' > etc/Brewfile
  - echo 'brew "zsh"' > etc/Brewfile-essentials

  - make
  - make bootstrap
  - make dotfiles
  - make code
  - make brew
  - make tools
