---
sudo: required
language: objective-c

# Reference for OS X Versions:
# https://docs.travis-ci.com/user/reference/osx/#macos-version
matrix:
  include:
    # Mojave (10.14)
    - os: osx
      osx_image: xcode11.3

script:
  - ./install
  - ./install -c code.conf.yml
