- name: Add Cask tap
  homebrew_tap: tap=homebrew/cask-fonts state=present

- name: Add Cask tap for alfred-numi
  homebrew_tap: tap=danielbayley/alfred state=present

- name: Update homebrew
  when: brew_update is not defined
  register: brew_update
  homebrew:
    update_homebrew: yes

- name: Install/Upgrade Cask packages
  ignore_errors: yes
  homebrew_cask:
    sudo_password: "{{ ansible_become_pass }}"
    name:
      - 1password
      - alfred
      - alfred-numi
      - android-file-transfer
      - arq
      - bartender
      - bettertouchtool
      - beardedspice
      - bitbar
      - browserosaurus
      - ccleaner
      - cyberduck
      - default-folder-x
      - dash
      # - disk-inventory-x
      - docker
      - dropbox
      - evernote
      - firefox
      - flux
      - font-firacode-nerd-font
      - google-backup-and-sync
      - google-chrome
      - google-cloud-sdk
      - growlnotify
      - iterm2
      - xquartz
      - hazel
      - istat-menus
      - karabiner-elements
      - keyboard-maestro
      - ngrok
      - omnifocus
      - postgres
      - rescuetime
      - setapp
      - shortcat
      - slack
      - sourcetree
      - spotify
      - startupizer
      - synergy
      - teamviewer
      - telegram
      - the-unarchiver
      - time-out
      - timing
      - visual-studio-code
      # - whatpulse # Error on install
      - whichspace
      - xld
      - zerotier-one
    state: present
