- name: Add Cask tap
  homebrew_tap: tap=homebrew/cask-fonts state=present

- name: Install Cask packages
  ignore_errors: yes
  homebrew_cask:
    name:
      - 1password
      - alfred
      - android-file-transfer
      - arq
      - bartender
      - bettertouchtool
      - bitbar
      - ccleaner
      - cyberduck
      - default-folder-x
      - dash
      - disk-inventory-x
      - docker
      - dropbox
      - evernote
      - firefox
      - flux
      - font-firacode-nerd-font
      - google-chrome
      - growlnotify
      - iterm2
      - xquartz
      - hazel
      - istat-menus
      - karabiner-elements
      - keyboard-maestro
      - ngrok
      - omnifocus
      - postgres
      - rescuetime
      - setapp
      - shortcat
      - slack
      - sourcetree
      - spotify
      - startupizer
      - synergy
      - teamviewer
      - telegram
      - the-unarchiver
      - time-out
      - visual-studio-code
      - whatpulse
      - whichspace
      - xld
    state: present
