- name: Add Homebrew Taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - koekeishiya/formulae

- name: Update homebrew
  when: brew_update is not defined
  register: brew_update
  homebrew:
    update_homebrew: yes

- name: Install/Upgrade Homebrew packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
    upgrade_all: yes
  with_items:
    - ansible
    - awsebcli
    - dfu-programmer
    - dfu-util
    - diff-so-fancy
    - { name: emacs, options: "with-cocoa,with-gnutls" }
    - entr
    - exercism
    - fzf
    - fzy
    - git
    - git-flow
    - hub
    - imagemagick
    - jq
    - koekeishiya/formulae/skhd
    - kubernetes-helm
    - mackup
    - magic-wormhole
    - mas
    - most
    - multitail
    - reattach-to-user-namespace
    - redis
    - ruby-build
    - terminal-notifier
    - tldr
    - tmux
    - nvim
    - yarn
    - yabai
    - yqrashawn/goku/goku

- name: Setup fzf
  command: /usr/local/opt/fzf/install --all
