- import_tasks: homebrew.yml
  tags:
    - homebrew

- import_tasks: cask.yml
  tags:
    - cask

- import_tasks: cask_upgrade.yml
  tags:
    - cask_upgrade

- import_tasks: mas.yml
  tags:
    - mas

- import_tasks: zsh.yml
  tags:
    - zsh

- import_tasks: mpd.yml
  tags:
    - mpd

- import_tasks: asdf.yml
  tags:
    - asdf

- import_tasks: docker.yml
  tags:
    - docker

- import_tasks: ruby.yml
  tags:
    - ruby

- import_tasks: local_sync.yml
  tags:
    - local_sync
