- import_tasks: cask_upgrade.yml
  tags:
    - cask_upgrade

- import_tasks: mpd.yml
  tags:
    - mpd

- import_tasks: local_sync.yml
  tags:
    - local_sync

- import_tasks: macos.yml
  tags:
    - macos

- import_tasks: asdf.yml
  tags:
    - asdf

- import_tasks: ruby.yml
  tags:
    - ruby

- import_tasks: docker.yml
  tags:
    - docker
