- name: Install zsh
  homebrew:
    name:
      - zsh
    state: present

- name: Ensure ~/.zinit path
  file: path=~/.zinit state=directory

- name: Install zinit
  git:
    repo: "https://github.com/zdharma/zinit.git"
    dest: "~/.zinit/bin"

- name: Set default shell to installed zsh
  become: yes
  user: name={{ansible_user_id}} shell=/usr/local/bin/zsh
