- name: Ensure Code Directory
  file: path=~/Code state=directory

- name: Clone Github Public Repos
  git:
    repo: "git@github.com:{{ item }}.git"
    dest: "~/Code/{{ item }}"
  with_items:
    - narze/baht
    - narze/mong
    - narze/puncome
    - narze/qmk_firmware
    - narze/resume
    - narze/switcheroo
    - narze/userscripts

- name: Add upstream remote for forks
  git_config:
    name: remote.upstream.url
    value: "{{ item.upstream }}"
    scope: local
    repo: "~/Code/{{ item.project }}"
  with_items:
    - { project: "narze/qmk_firmware", upstream: "git@github.com:qmk/qmk_firmware.git" }
