# Asdf dependencies
- brew:
  - coreutils
  - automake
  - autoconf
  - openssl
  - libyaml
  - readline
  - libxslt
  - libtool
  - unixodbc
  - unzip
  - curl

- shell:
  - description: Clone asdf
    quiet: true
    command: |
      if cd ~/.asdf;
      then git pull origin v0.7.7;
      else git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.7;
      fi
