# Asdf dependencies
- brew:
  - coreutils
  - automake
  - autoconf
  - openssl
  - libyaml
  - readline
  - libxslt
  - libtool
  - unixodbc
  - unzip
  - curl

- shell:
  - description: Clone asdf
    quiet: true
    command: |
      if cd ~/.asdf;
      then git pull origin v0.7.6;
      else git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.6;
      fi

- asdf:
  - plugin: nodejs
    url: https://github.com/asdf-vm/asdf-nodejs.git
    global: 12.16.0
    versions:
      - 12.16.0
  - plugin: ruby
    url: https://github.com/asdf-vm/asdf-ruby.git
    global: 2.6.5
    versions:
      - 2.6.5
