- asdf:
  - plugin: nodejs
    url: https://github.com/asdf-vm/asdf-nodejs.git
    global: 12.16.0
    versions:
      - 12.16.0
  - plugin: ruby
    url: https://github.com/asdf-vm/asdf-ruby.git
    global: 2.6.5
    versions:
      - 2.6.5
