- brew:
    - fish

# Setup Fisher
- shell:
    - description: Setup Fisher
      command: |
        curl -sL https://git.io/fisher > /tmp/fisher.fish;
        fish -c 'source /tmp/fisher.fish && fisher update';
