- defaults:
    link:
      relink: true

- clean: ['~']

- create:
  - ~/.bundle
  - ~/.config
  - ~/.config/kitty
  - ~/.hushlogin
  - ~/Library/Scripts
  - ~/mnt
  # Alfred workflows fix
  - ~/Library/Caches/com.runningwithcrayons.Alfred-2
  - ~/Library/Application Support/Alfred 2

- link: # /dotfiles == /.dotfiles == /laptop
    ~/.dotfiles:
      force: true
      path: ''
    ~/laptop:
      path: ~/dotfiles

- link:
    ~/.asdfrc:
      path: ~/.dotfiles/etc/asdfrc
    ~/.Brewfile:
      path: ~/.dotfiles/etc/Brewfile
    ~/.Brewfile-essentials:
      path: ~/.dotfiles/etc/Brewfile-essentials
    ~/.bundle/config:
      path: ~/.dotfiles/etc/bundle_config
    ~/.config/karabiner.edn:
      path: ~/.dotfiles/etc/karabiner.edn
    ~/.config/kitty/kitty.conf:
      path: ~/.dotfiles/etc/kitty.conf
    ~/.config/kitty/theme.conf:
      path: ~/.dotfiles/etc/SpaceGray.conf
    ~/.config/synthwave84.css:
      path: ~/.dotfiles/etc/synthwave84.css
    ~/.default-gems:
      path: ~/.dotfiles/etc/default-gems
    ~/.duti:
      path: ~/.dotfiles/etc/duti
    ~/.editorconfig:
      path: ~/.dotfiles/etc/editorconfig
    ~/.gemrc:
      path: ~/.dotfiles/etc/gemrc
    ~/.gitconfig:
      path: ~/.dotfiles/etc/gitconfig
    ~/.gitignore_global:
      path: ~/.dotfiles/etc/gitignore_global
    ~/.hyper.js:
      path: ~/.dotfiles/etc/hyper.js
      force: true
    ~/.mackup:
      path: ~/.dotfiles/etc/mackup
    ~/.mackup.cfg:
      path: ~/.dotfiles/etc/mackup.cfg
    ~/.p10k.zsh:
      path: ~/.dotfiles/zsh/p10k.zsh
    ~/.pryrc:
      path: ~/.dotfiles/etc/pryrc
    ~/.skhdrc:
      path: ~/.dotfiles/etc/skhdrc
    ~/.tmux.conf:
      path: ~/.dotfiles/etc/tmux/.tmux.conf
    ~/.tmux.conf.local:
      path: ~/.dotfiles/etc/tmux/.tmux.conf.local
    ~/.yabai_axunknown_float:
      path: ~/.dotfiles/etc/yabai_axunknown_float
    ~/.yabai_focus_display:
      path: ~/.dotfiles/etc/yabai_focus_display
    ~/.yabai_monocle:
      path: ~/.dotfiles/etc/yabai_monocle
    ~/.yabai_rules:
      path: ~/.dotfiles/etc/yabai_rules
    ~/.yabairc:
      path: ~/.dotfiles/etc/yabairc
    ~/.zshrc:
      path: ~/.dotfiles/zsh/zshrc
    ~/.zinit_rc:
      path: ~/.dotfiles/zsh/zshrc
    ~/.omz_rc:
      path: ~/.dotfiles/zsh/omz
    ~/Library/Scripts/:
      glob: true
      path: ~/.dotfiles/etc/applescripts/*
      relink: true
