- create:
  - ~/.config
  - ~/.local

- link:
    ~/.config/tmuxinator:
      force: true
      path: "~/Sync/laptop_local/tmuxinator"
    ~/.local/mpd:
      force: true
      path: "~/Sync/laptop_local/mpd"
