- shell:
  - description: Zinit self update
    command: zsh -i -c "zinit self-update"
  - description: Zinit update
    command: zsh -i -c "zinit update"

  - description: Brew update
    command: brew update
  - description: Cask update
    command: brew cu -acy
